development:
  adapter: postgresql
  encoding: utf8
  database: techblog_development
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: techblog_test
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: techblog_production
  host: localhost
